//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokuCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioTrack
    {
        public System.Guid AudioTrackid { get; set; }
        public System.Guid VideoReleaseId { get; set; }
        public System.Guid LanguageId { get; set; }
        public string AudioTrackName { get; set; }
        public string AudioTrackDescription { get; set; }
        public string Channel { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual VideoRelease VideoRelease { get; set; }
    }
}
