//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokuCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioTrackType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AudioTrackType()
        {
            this.AudioTracks = new HashSet<AudioTrack>();
        }
    
        public System.Guid AudioTrackTypeId { get; set; }
        public System.Guid LanguageId { get; set; }
        public string AudioTrackName { get; set; }
        public string AudioTrackDescription { get; set; }
        public string Channel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AudioTrack> AudioTracks { get; set; }
        public virtual Language Language { get; set; }
    }
}
