
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TokuCinema.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Language
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Language()
    {

        this.AudioTracks = new HashSet<AudioTrack>();

        this.SubtitleTracks = new HashSet<SubtitleTrack>();

    }


    public System.Guid LanguageId { get; set; }

    public string LanguageName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AudioTrack> AudioTracks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SubtitleTrack> SubtitleTracks { get; set; }

}

}
