//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokuCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaFile
    {
        public System.Guid MediaFielId { get; set; }
        public System.Guid VideoReleaseId { get; set; }
        public byte[] MediaFile1 { get; set; }
        public bool Image { get; set; }
        public bool Video { get; set; }
        public int Location { get; set; }
        public string VideoLink { get; set; }
    
        public virtual VideoRelease VideoRelease { get; set; }
    }
}
