//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokuCinema.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class MediaFile
    {
        public System.Guid MediaFileId { get; set; }
        public System.Guid VideoVersionId { get; set; }
        public byte[] MediaFile1 { get; set; }
        public bool Image { get; set; }
        public bool Video { get; set; }
        public int Location { get; set; }
        public bool UseFileOverLink { get; set; }
        public string MediaLink { get; set; }
        
        // Used for file uploads
        public HttpPostedFileBase File { get; set; }

        public virtual VideoVersion VideoVersion { get; set; }
    }
}
