//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokuCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingItemType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingItemType()
        {
            this.VideoShoppingItems = new HashSet<VideoShoppingItem>();
        }
    
        public System.Guid ShoppingItemTypeId { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid ShoppingItemName { get; set; }
        public System.Guid PurchaseLink { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoShoppingItem> VideoShoppingItems { get; set; }
    }
}
