//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokuCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubtitleTrackType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubtitleTrackType()
        {
            this.SubtitleTracks = new HashSet<SubtitleTrack>();
        }
    
        public System.Guid SubtitleTrackTypeId { get; set; }
        public System.Guid LanguageId { get; set; }
        public string SubtitleTrackName { get; set; }
        public string SubtitleTrackDescription { get; set; }
    
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubtitleTrack> SubtitleTracks { get; set; }
    }
}
