//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokuCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubtitleTrack
    {
        public System.Guid SubtitleTrackId { get; set; }
        public System.Guid VideoVersionId { get; set; }
        public System.Guid SubtitleTrackTypeId { get; set; }
    
        public virtual SubtitleTrackType SubtitleTrackType { get; set; }
        public virtual VideoVersion VideoVersion { get; set; }
    }
}
