//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokuCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoVersionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VideoVersionType()
        {
            this.VideoVersions = new HashSet<VideoVersion>();
        }
    
        public System.Guid VideoVersionTypeId { get; set; }
        public string VideoVersionTitle { get; set; }
        public string VideoVersionDescription { get; set; }
        public System.Guid VideoMediaId { get; set; }
        public string AspectRatio { get; set; }
        public Nullable<int> Runtime { get; set; }
        public Nullable<int> ChapterStops { get; set; }
    
        public virtual VideoMedia VideoMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoVersion> VideoVersions { get; set; }
    }
}
