//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokuCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoMedia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VideoMedia()
        {
            this.VideoReleases = new HashSet<VideoRelease>();
            this.VideoVersions = new HashSet<VideoVersion>();
        }
    
        public System.Guid VideoMediaId { get; set; }
        public System.Guid MediaId { get; set; }
        public string OriginalAspectRatio { get; set; }
        public int OriginalRuntime { get; set; }
        public System.DateTime ReleaseDate { get; set; }

        //From Media
        public string MediaOfficialTitle { get; set; }
        public string MediaDescription { get; set; }
        public string WikipediaLink { get; set; }

        public virtual Medium Medium { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoRelease> VideoReleases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoVersion> VideoVersions { get; set; }
    }
}
