//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokuCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoReview
    {
        public System.Guid VideoReviewId { get; set; }
        public System.Guid VideoVersionId { get; set; }
        public string Introduction { get; set; }
        public string PresentationComments { get; set; }
        public int PresentationScore { get; set; }
        public string VideoComments { get; set; }
        public int VideoScore { get; set; }
        public string AudioComments { get; set; }
        public int AudioScore { get; set; }
        public string BonusFeatureComments { get; set; }
        public int BonusFeatureScore { get; set; }
        public string VerdictComments { get; set; }
        public int VerdictScore { get; set; }
    
        public virtual VideoVersion VideoVersion { get; set; }
    }
}
