//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokuCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoVersion
    {
        public System.Guid VideoVersionId { get; set; }
        public System.Guid VideoVersionTypeId { get; set; }
        public System.Guid VideoReleaseId { get; set; }
        public System.Guid VideoMediaId { get; set; }
    
        public virtual VideoRelease VideoRelease { get; set; }
        public virtual VideoVersionType VideoVersionType { get; set; }
        public virtual VideoMedia VideoMedia { get; set; }
    }
}
